# Command: Python Code Conformance  
# Systematically conform Python code to project style and practice standards

[context]
name = 'cs-conform-python'
description = 'Systematically conform Python code to project style and practice standards'

# Additional context fields
color = 'green'
permissions = ['read', 'write']