[context]
name = 'cs-manage-prd'
description = 'Manage product requirements documents and feature planning'
allowed-tools = [
    # Built-in tools (semantic names)
    'read',
    'write',
    'edit',
    'multi-edit',
    'list-directory',
    'glob',
    'grep',
]
permissions = ['read', 'write']
