#!/usr/bin/env bash

npm install --global @openai/codex
npm install --global @google/gemini-cli
npm install --global opencode-ai@latest
# npm install --global @qwen-code/qwen-code@latest
curl -LsSf https://code.kimi.com/install.sh | bash

npm install --global difit
npm install --global @fission-ai/openspec@latest
