name: copier

on:
  pull_request:
    branches: [ '*' ]
    paths:
      - '.github/workflows/validate-template.yaml'
      - '.auxiliary/configuration/copiertv/**'
      - 'copier.yaml'
      - 'template/**'
      - 'tests/data/profiles/**'
      - 'sources/agentsmgr/cmdbase.py'
      - 'sources/agentsmgr/population.py'
  push:
    branches: [ 'master' ]
    paths:
      - '.github/workflows/validate-template.yaml'
      - '.auxiliary/configuration/copiertv/**'
      - 'copier.yaml'
      - 'template/**'
      - 'tests/data/profiles/**'
      - 'sources/agentsmgr/cmdbase.py'
      - 'sources/agentsmgr/population.py'
  workflow_dispatch: {}

jobs:

  initialize:
    uses: ./.github/workflows/core--initializer.yaml

  validate-template:
    needs: [ initialize ]
    name: Validate Copier Template (${{ matrix.variant }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [ 'default', 'maximum' ]

    steps:

      - name: Prepare Python
        uses: emcd/python-project-common/.github/actions/python-hatch@gha-1
        with:
          python-version: ${{ fromJSON(needs.initialize.outputs.python-versions)[0] }}

      - name: Install Copiertv
        run: pip install copiertv

      - name: Validate Content Variant
        run: |
          hatch --env develop run \
            agentsmgr generate \
            --variant ${{ matrix.variant }}

      - name: Validate Template Variant
        run: copiertv validate ${{ matrix.variant }}